### ISSUE TITLE
Изменение глобальных переменных

### ISSUE THREAD

**Issue by vporoshok** [evtatarintsev/elma-bpm#1]
По заданию всё сделано отлично. Но возник вопрос по тесту: на уровне теста переопределяется глобальная переменная os.Stdout и os.Stderr. Это может привести к плачевным последствиям, если рядом, например, окажется ещё один тест, который тоже подменяет эти переменные. Как лучше переписать тест, чтобы не было побочных эффектов?

**Comment by evtatarintsev** [comment]
В данном случае, тесты выполняются последовательно и все ок, но согласен, что это плохое решение, к тому же писать в файл без необходимости тоже так себе вариант.

Изменил printResults

> printResults(w io.Writer, results chan Result)

теперь она принимает Writer и пишет куда указано, в тестах пишу в буфер

PR https://github.com/evtatarintsev/elma-bpm/pull/2/files

**Comment by vporoshok** [comment]
отлично!
